name: Publish Book

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
          
      - name: Install TinyTeX
        run: |
          quarto install tinytex
          
      - name: Make scripts executable
        run: |
          chmod +x scripts/update-index.sh
          
      - name: Update book index
        run: |
          ./scripts/update-index.sh
          
      - name: Render Book
        run: |
          quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            _book/*.pdf
            _book/*.epub
          name: Book Release ${{ github.ref_name }}
          tag_name: v${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
